### ISSUE TITLE
How to realize the historm matching between MUAD and Cityscapes

### ISSUE THREAD

**Issue by delaprada** [ENSTA-U2IS/MUAD-Dataset#4]
Hi! Thanks for providing this good work.

I have read the paper and this statement in the paper indicate that model trained on MUAD images modified with simple histogram matching with Cityscapes images can achieve better results than w/o histogram matching.

I am curious about how to choose the reference image for histogram matching. Is the reference image randomly chosen from the target dataset(Cityscapes)?

Thank you!

**Comment by giannifranchi** [comment]
For each image of MUAD, we randomly select an image of Cityscape dataset and perform histogram matching.
Here is a tutorial on histogram matching https://scikit-image.org/docs/stable/auto_examples/color_exposure/plot_histogram_matching.html
best
